### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ucbjrl**
Fix for #27

### CODE REVIEW

**Comment by ucbjrl** [comment]
Good point @edwardcwang . I believe @chick has instructions in the `README.md` for initializing a real project using this template. I'll update them to include removal/updating of the `LICENSE`.

**Comment by chick** [comment]
@edwardcwang @ucbjrl Not that I want to drag this out, but would it be better to rename the License file to SAMPLE.LICENSE with instructions to re-name it, or provide another in the README. Splitting hairs, but I think that would protect against TLDR and the university ultimately owning all software.

**Comment by ucbjrl** [comment]
But it is the template code we're licensing. I don't know the legal difference between LICENSE and SAMPLE-LICENSE.

**Comment by chick** [comment]
That makes sense, so best to leave it.

**Comment by edwardcwang** [comment]
2 thoughts.

1) Instead of putting the code in LICENSE, we could just put it at the bottom of README.md and mention in a line above it that "the following code only applies to the template code". Avoids any LICENSE contamination.

2) How important is it to copyright sample/template code anyway? BSD license requires you to include the original code's copyright notices which maybe doesn't make sense for commercial chip projects using Chisel template code. Maybe we could just make the template CC0/public-domain and so avoid any issues with user code being copyrighted?

https://creativecommons.org/share-your-work/public-domain/cc0/

**Comment by ucbjrl** [comment]
I'd like to follow up on @edwardcwang's suggestion and update the license references in the code to refer to the README, and add the following text (http://unlicense.org/) to the README:

```
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>
```

**Comment by edwardcwang** [comment]
@ucbjrl Do you want to just go ahead and update the PR, then we can move forward?

**Pull request merged**
